### ISSUE TITLE
签到加入了人机验证

### ISSUE THREAD

**Issue by Johnnyarch** [fengwenhua/hifini_sign_in#3]
网页签到加入了人机验证，原来的脚本无法签到了

**Comment by KunCheng-He** [comment]
我是最近才遇到的这个问题，我以为是封了我服务器的IP，我换了地区的服务器也不行，手动签到现在是正常的。

**Comment by fengwenhua** [comment]
感谢提醒，已修复，你们可以测试一下看看效果，我测试了一天，可以正常使用。后续有问题可以再反馈。
