### ISSUE TITLE
网站签到防人机升级了，签到脚本失效

### ISSUE THREAD

**Issue by WeberLeah** [fengwenhua/hifini_sign_in#6]
网站签到防人机升级了，访问网站现在有个跳转页面

**Comment by lywly** [comment]
> 网站签到防人机升级了，访问网站现在有个跳转页面

## 开始执行... 2024-12-19 09:55:54


xxxxxxxxxxxx
No sign value found.

## 执行结束... 2024-12-19 09:55:55  耗时 1 秒

**Comment by WeberLeah** [comment]
网站恢复了
